[keycloak_servers]
# Add your VM hostnames or IPs here
# keycloak01.example.com
# keycloak02.example.com
# 192.168.1.50

[keycloak_servers:vars]
ansible_user=root
# ansible_ssh_private_key_file=~/.ssh/id_rsa
