---
galaxy_info:
  role_name: keycloak_clients
  author: AppDev CoP
  description: Manage Keycloak clients and client roles using redhat.rhbk
  license: Apache-2.0
  min_ansible_version: "2.16"
  galaxy_tags: [keycloak, client, rhbk, oidc]
dependencies: []
