apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
    chart: minio-5.4.0
    release: my-minio
  name: my-minio
  namespace: open-s3-minio
type: Opaque
stringData:
  rootUser: minioadmin
  rootPassword: minio-strong-password
