---
- name: "Create ServiceAccount: {{ item.namespace }}/{{ item.name }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
        labels:
          app.kubernetes.io/managed-by: keycloak-ops
  loop: "{{ openshift_rbac_service_accounts }}"
  loop_control:
    label: "{{ item.namespace }}/{{ item.name }}"
