---
- name: Deploy systemd unit file
  ansible.builtin.template:
    src: keycloak.service.j2
    dest: "/etc/systemd/system/{{ keycloak_vm_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: restart keycloak

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Keycloak service
  ansible.builtin.systemd:
    name: "{{ keycloak_vm_service_name }}"
    enabled: "{{ keycloak_vm_service_enabled }}"
    state: "{{ keycloak_vm_service_state }}"
