mp.messaging.outgoing.quotes-out.connector=smallrye-kafka
mp.messaging.outgoing.quotes-out.topic=quotes
mp.messaging.outgoing.quotes-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.quotes-in.connector=smallrye-kafka
mp.messaging.incoming.quotes-in.topic=quotes
mp.messaging.incoming.quotes-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
